version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g @google/clasp
      - which clasp
      - clasp --version

  pre_build:
    commands:
      - |
        aws secretsmanager get-secret-value \
          --secret-id clasp/auth/google \
          --query SecretString --output text | jq '{
            token: {
              access_token: .tokens.default.access_token,
              refresh_token: .tokens.default.refresh_token,
              token_type: "Bearer",
              expiry_date: (now * 1000 + 604800000)
            }
          }' > ~/.clasprc.json

      - echo "=== CHECK TOKEN ==="
      - cat ~/.clasprc.json | jq '.token.access_token' || exit 1

  build:
    commands:
      - echo "Attempting clasp push to Google Apps Script..."
      - clasp push -f
      - echo "Successfully pushed to Google Apps Script!"

artifacts:
  files:
    - '**/*'