version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g @google/clasp
  pre_build:
    commands:
      # Putting Secret From AWS Secrets Manager Into File For Clasp 
      - echo $CLASP_AUTH > ~/.clasprc.json
  build:
    commands:
      - echo "Pushing code to Google Apps Script..."
      - clasp push -f
artifacts:
  files:
    - '**/*'